# Generated by Django 5.2.16 on 2026-07-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="emergency_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
